### ISSUE TITLE
The repository link for `slice-dst` points to `erasable`

### ISSUE THREAD

**Issue by HeroicKatora** [CAD97/pointer-utils#42]
https://github.com/CAD97/pointer-utils/blob/c8b4f701463a24e3be851d2b74537cd91fc03bf1/crates/slice-dst/Cargo.toml#L8

**Comment by CAD97** [comment]
...whoops

**Comment by CAD97** [comment]
[Published 1.1.2 with the manifest fix.](https://crates.io/crates/slice-dst/1.1.2)
