### ISSUE TITLE
slice-dst: Is it possible to add metadata to an existing (string) slice?

### ISSUE THREAD

**Issue by jplatte** [CAD97/pointer-utils#66]
Currently, I don't see a way of creating `&SliceWithHeader<Header, T>` from a `Header` + `&[T]`, or `&StrWithHeader<Header>` from `Header` + `&str`. Would this generally be possible?

**Comment by CAD97** [comment]
This isn't possible, because these types store the header alongside the slice in the same allocation.

**Comment by jplatte** [comment]
I suspected as much. I think I'm still not understanding some important of how to use this crate for my needs, but maybe I should just stop trying to replicate everything the previous API did and in the end things will sort themselves out 🤷‍♂️
